### ISSUE TITLE
Instability occurs at a n2π rotation

### ISSUE THREAD

**Issue by santiago-correa-89** [ONSAS/ONSAS#703] opened 2024-05-29 17:56 UTC
A instability computing the solution of rotational structures is observed at n*2*pi rotations. The figure shows a oscillation of the parameter nodal displacement  in the direction of the force when n*2pi is reached. 

The code to reproduce the problem is a modification of the simplePropeller.m example. In this case the rigidity was modify compared to the original example.

<img width="506" alt="Captura de pantalla 2024-05-29 a la(s) 14 49 17" src="https://github.com/ONSAS/ONSAS/assets/70283425/82b9678c-61d5-47a6-8bc7-63e65686885e">

[exampleFiles.zip](https://github.com/ONSAS/ONSAS/files/15488876/exampleFiles.zip)

**Comment by jorgepz** [comment] 2024-05-30 19:59
I did some tests and confirmed the behavior also with non reference canonical blade direction, thus I think it is not related to rotations/changes of systems of coordinates.

![image](https://github.com/ONSAS/ONSAS/assets/42485529/b1a8c0ef-986b-4f0c-8c73-6933fc83c88f)

The issue is open to be solved, but I am not sure it is a bug. Could be due to a numerical instability since also the system has a period 2pi.

This is a nice topic to study in an article!

**Comment by santiago-correa-89** [comment] 2024-05-31 14:56
This is really interesting; it could be directly related to resolving the problem. Two options: adding an epsilon close to the n2π position might slightly avoid the numerical issue, or adding damping could change the problem's nature and create a smoother solution?

**Comment by jorgepz** [comment] 2024-05-31 22:12
yes. we can discuss it next week

**Comment by mvanzulli** [comment] 2024-06-01 21:05
I have observed that behavior in from time to time while prototyping examples. Could be related to #117

**Comment by santiago-correa-89** [comment] 2024-06-01 23:10
Great! I will take a look, maybe avoiding that singularity that instability can be avoided.

**Comment by jorgepz** [comment] 2024-06-03 22:34
i think that the root of the problem is:

```matlab
octave:30> expm(skew([0,0,-1e-4]))
ans =

   1.0000   0.0001        0
  -0.0001   1.0000        0
        0        0   1.0000

octave:31> expm(skew([0,0,1e-4]))
ans =

   1.0000  -0.0001        0
   0.0001   1.0000        0
        0        0   1.0000
```

It seems that this is an issue of co-rotational formulations: 
https://doi.org/10.1145/2994258.2994269

**Comment by santiago-correa-89** [comment] 2024-06-04 15:06
This is the link to the Le Thanh-Nam Le work. In his work is explained the limitation of adding the rotation when 2π angle is reached. 

https://files.eccomasproceedia.org/papers/compdyn-2013/C1592.pdf?mtime=20170330154656

This is a capture of the work. Maybe it is needed to add the incremental rotation procedure.

<img width="723" alt="Captura de pantalla 2024-06-03 a la(s) 5 42 15 p  m" src="https://github.com/ONSAS/ONSAS/assets/70283425/10c11882-b3ec-42af-b2e9-900c1555187d">

**Comment by jorgepz** [comment] 2024-06-05 11:19
the other resource is http://dx.doi.org/10.1016/j.cma.2013.11.007 where they mention other strategies for update.

I think this is already clear that the instability is due to the update strategy, therefore I am closing this issue and https://github.com/ONSAS/ONSAS/issues/117 remains open as a to-do feature for the near future.

**Closed by jorgepz** 2024-06-05 11:19 UTC
Labels: strange
